//! Raw FFI bindings to the vendored GNU Units C library.
//!
//! Generated by `bindgen`; not intended for direct use, prefer the safe
//! wrappers in the `gnu_units` crate.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::ptr_offset_with_cast)]
#![allow(unnecessary_transmutes)]

include!("../gen/bindings.rs");
